# Generated by Django 5.1.4 on 2024-12-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmeApp', '0002_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='dis_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
