# Generated by Django 5.1.4 on 2024-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmeApp', '0004_garage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model_name',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
