# Generated by Django 5.1.4 on 2024-12-16 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmeApp', '0006_washingbay_alter_car_image_alter_car_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(14)])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address')])),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
