# Generated by Django 5.1.4 on 2025-01-08 07:33

import django_google_maps.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmeApp', '0010_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
    ]
