# Generated by Django 5.1.4 on 2025-01-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmeApp', '0011_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='latitude',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garage',
            name='longitude',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
