# Generated by Django 5.1.4 on 2025-01-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixmeApp', '0014_message_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
