# Generated by Django 5.1.4 on 2025-01-25 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmeApp', '0015_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='vehicle_make',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='fixmeApp.carbrand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.JSONField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='brand_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
